# YAML configuration file for loading default parameters into PubsliherNodelet
capture_path: ""
capture_loop: true
sensor_ports: []  # Empty list means use default port 8808. Can specify multiple ports like [8808, 8809]
include_saturated_points: true
include_second_return_points: true
include_invalid_points: false
include_noise_points: false
include_blocked_points: true
include_ambient_points: true # set to false if ambient mode is not enabled from firmware
output_by_handle: true
output_by_sn: true
min_altitude: -90.
max_altitude: 90.
min_azimuth: -90.
max_azimuth: 90.
min_distance: 0.0
max_distance: 1000.0

# In ROS, unlike in ROS2, this needs to be set to an empty 
# list if not using the expected lidars feature.
expected_sensor_ips: []
